---   #sudo pip install boto
- name: Creates ec2 instance
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
  - name: Create instances
    ec2:
      key_name: team_4
      instance_type: t2.medium
      image: ami-06d2998e9c3af0a0a
      count: 1
      region: us-west-2
      vpc_subnet_id: subnet-955011be
      assign_public_ip: yes